# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-01 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('reponame', models.CharField(max_length=255)),
                ('ipfs_hash', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'repo',
            },
        ),
    ]
