# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-01 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0003_authority_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authority',
            name='user_type',
            field=models.CharField(default=b'owner', max_length=255),
        ),
    ]
