# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-07 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0004_auto_20181001_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authority',
            name='user_type',
            field=models.CharField(default='owner', max_length=255),
        ),
    ]
